import {
  ACCENT,
  ACCENT_LIGHT,
  BG,
  BORDER,
  BORDER_DEFAULT,
  BORDER_LIGHT,
  CARD_BG,
  GREEN,
  ORANGE,
  PLACEHOLDER,
  RED,
  SHADOW,
  STAR_COLOR,
  TEXT_INVERSE,
  TEXT_MUTED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_TERTIARY,
} from '@/utils/constants';
import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  content: {
    padding: 16,
    paddingBottom: 28,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  photoMessage: {
    marginTop: -4,
    marginBottom: 16,
    fontSize: 13,
    color: TEXT_TERTIARY,
    textAlign: 'center',
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: CARD_BG,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  profileHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  profileHeaderName: {
    fontSize: 20,
    fontWeight: '800',
    color: TEXT_PRIMARY,
  },
  profileHeaderUsername: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    color: TEXT_TERTIARY,
  },
  profileHeaderMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 10,
  },
  profileHeaderStars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileRatingNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: '#444',
    minWidth: 28,
  },
  profileRatingNew: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT_MUTED,
  },
  roleBadge: {
    backgroundColor: '#EEF2FF',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  roleBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4338CA',
  },
  section: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: TEXT_TERTIARY,
    marginBottom: 6,
  },
  profileCard: {
    backgroundColor: CARD_BG,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
    padding: 14,
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    marginBottom: 12,
  },
  helperText: {
    marginTop: 8,
    fontSize: 12,
    color: TEXT_TERTIARY,
  },
  input: {
    backgroundColor: CARD_BG,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
    color: TEXT_PRIMARY,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  infoBox: {
    backgroundColor: CARD_BG,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
  },
  infoText: {
    fontSize: 16,
    color: TEXT_PRIMARY,
  },

  carDetailsCard: {
    backgroundColor: CARD_BG,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
    padding: 14,
    marginBottom: 20,
  },
  carDetailsHeader: {
    paddingBottom: 10,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  carDetailsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  carDetailsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  carDetailsField: {
    flex: 1,
  },
  carDetailsFieldFull: {
    width: '100%',
  },
  carDetailsInfoBox: {
    paddingVertical: 12,
  },
  carDetailsPhotoBox: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  carDetailsPhotoLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  carDetailsPhotoIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: BG,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#eee',
  },
  carDetailsPhotoHint: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT_TERTIARY,
  },
  carDetailsPhotoPreview: {
    width: 56,
    height: 56,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e5e5',
    backgroundColor: BG,
  },
  carPhotoMessage: {
    marginTop: 8,
    fontSize: 13,
    color: TEXT_TERTIARY,
  },
  profileMessage: {
    marginTop: -10,
    marginBottom: 18,
    fontSize: 13,
    color: TEXT_TERTIARY,
    textAlign: 'center',
  },
  
  saveButton: {
    flexDirection: 'row',
    backgroundColor: ACCENT,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 8,
  },
  accountCenterButton: {
    flexDirection: 'row',
    backgroundColor: '#6366F1',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 8,
  },
  accountCenterButtonText: {
    color: TEXT_INVERSE,
    fontSize: 16,
    fontWeight: '600',
  },

  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: TEXT_INVERSE,
    fontSize: 18,
    fontWeight: '600',
  },
  settingsSection: {
    backgroundColor: CARD_BG,
    borderRadius: 12,
    marginBottom: 24,
    overflow: 'hidden',
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  settingText: {
    flex: 1,
    fontSize: 16,
    color: TEXT_PRIMARY,
    marginLeft: 12,
  },
  signOutButton: {
    backgroundColor: RED,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 32,
  },
  signOutButtonText: {
    color: TEXT_INVERSE,
    fontSize: 18,
    fontWeight: '600',
  },

  settingsGroupTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: TEXT_TERTIARY,
    marginBottom: 8,
    marginTop: 8,
    marginLeft: 4,
  },
  settingDangerText: {
    flex: 1,
    fontSize: 16,
    color: RED,
    marginLeft: 12,
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: BG,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: CARD_BG,
    borderBottomWidth: 1,
    borderBottomColor: BORDER_DEFAULT,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: TEXT_PRIMARY,
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    flex: 1,
    padding: 16,
  },
  modalMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: CARD_BG,
    borderRadius: 12,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
  },
  modalMenuText: {
    fontSize: 16,
    color: TEXT_PRIMARY,
    fontWeight: '500',
  },
  activityMessage: {
    marginTop: 10,
    marginBottom: 6,
    fontSize: 13,
    color: TEXT_PRIMARY,
  },
  activitySectionTitle: {
    marginTop: 16,
    marginBottom: 8,
    fontSize: 16,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  activitySubtle: {
    fontSize: 13,
    color: TEXT_TERTIARY,
    marginBottom: 8,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: CARD_BG,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  activityRowLeft: {
    flex: 1,
    paddingRight: 12,
  },
  activityName: {
    fontSize: 14,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  activityRole: {
    marginTop: 2,
    fontSize: 12,
    color: TEXT_TERTIARY,
  },
  activityActionButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  activityActionText: {
    fontSize: 13,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
    backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  backRowText: {
    fontSize: 15,
    color: '#6366F1',
    fontWeight: '600',
    marginLeft: 4,
  },
  subSectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: TEXT_PRIMARY,
    marginBottom: 16,
  },
  temporaryMessage: {
    backgroundColor: '#EEF2FF',
    color: '#4338CA',
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    fontSize: 14,
  },
 
  accountCenterMessage: {
    fontSize: 14,
    color: '#6366F1',
    marginBottom: 16,
  },

  choiceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: CARD_BG,
    borderRadius: 12,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
  },
  choiceRowText: {
    fontSize: 16,
    color: TEXT_PRIMARY,
    fontWeight: '500',
  },
  choiceRowValue: {
    fontSize: 16,
    color: '#6366F1',
    fontWeight: '700',
  },
  choiceGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  choicePill: {
    backgroundColor: CARD_BG,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
  },
  choicePillActive: {
    borderColor: '#6366F1',
    backgroundColor: '#EEF2FF',
  },
  choicePillText: {
    fontSize: 14,
    color: TEXT_PRIMARY,
    fontWeight: '600',
  },
  choicePillTextActive: {
    color: '#4338CA',
  },
});
