import {
  ACCENT,
  ACCENT_LIGHT,
  BG,
  BORDER,
  BORDER_DEFAULT,
  BORDER_LIGHT,
  CARD_BG,
  GREEN,
  ORANGE,
  PLACEHOLDER,
  RED,
  SHADOW,
  STAR_COLOR,
  TEXT_INVERSE,
  TEXT_MUTED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_TERTIARY,
} from '@/utils/constants';
import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },

  // ── Header actions
  addButton: {
    backgroundColor: ACCENT,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── List
  listContent: { padding: 16, paddingBottom: 48 },

  // ── Day accordion
  daySection: {
    backgroundColor: CARD_BG,
    borderRadius: 14,
    marginBottom: 10,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    overflow: "hidden",
  },
  daySectionOpen: {
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  dayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  dayHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  dayName: { fontSize: 16, fontWeight: "600", color: TEXT_PRIMARY },
  dayNameOpen: { color: ACCENT },
  dotRow: { flexDirection: "row", gap: 5 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  dotGreen: { backgroundColor: GREEN },
  dotBlue: { backgroundColor: ACCENT },
  dayBody: {
    paddingHorizontal: 18,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: BG,
    paddingTop: 16,
  },

  // ── Section labels
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8e8e93",
    letterSpacing: 0.6,
    marginBottom: 10,
  },
  emptyNote: {
    fontSize: 13,
    color: "#aeaeb2",
    fontStyle: "italic",
    marginBottom: 4,
  },

  // ── Availability row (driver)
  availRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#f0fdf4",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  availDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: GREEN,
  },
  availText: { flex: 1, fontSize: 14, fontWeight: "500", color: "#16a34a" },
  availDelete: { padding: 2 },

  // ── Ride row (driver)
  rideRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
    borderWidth: 1,
  },
  rideRowPending: { backgroundColor: "#fff8f0", borderColor: "#fdd9a0" },
  rideRowConfirmed: { backgroundColor: "#eff6ff", borderColor: "#bfdbfe" },
  rideRowLeft: { flex: 1, gap: 2 },
  rideRowName: { fontSize: 14, fontWeight: "600", color: TEXT_PRIMARY },
  rideRowTime: { fontSize: 12, color: "#636366" },
  rideRowRight: { flexDirection: "row", alignItems: "center", gap: 6 },
  statusPill: {
    borderRadius: 20,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  pillPending: { backgroundColor: ORANGE },
  pillAwaiting: { backgroundColor: "#8e8e93" },
  pillConfirmed: { backgroundColor: ACCENT },
  statusPillText: { color: TEXT_INVERSE, fontSize: 11, fontWeight: "700" },

  // ── Rider ride card
  riderRideCard: {
    backgroundColor: "#f9f9fb",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: BORDER,
  },
  riderRideCardConfirmed: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
  },
  riderRideCardRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  routeViz: { alignItems: "center", marginRight: 12, paddingTop: 2, gap: 3 },
  routeDotGreen: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: GREEN,
  },
  routeVizLine: {
    width: 2,
    height: 18,
    backgroundColor: "#d1d1d6",
    marginVertical: 2,
  },
  routeInfo: { flex: 1, gap: 4 },
  routeAddr: { fontSize: 14, fontWeight: "500", color: TEXT_PRIMARY },
  routeTimeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginVertical: 2,
  },
  routeTimeTxt: { fontSize: 12, color: "#8e8e93" },
  riderRideDelete: { padding: 4, marginLeft: 6 },
  incomingRequestBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: ACCENT_LIGHT,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  incomingRequestLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  incomingRequestText: {
    fontSize: 13,
    color: "#1d4ed8",
    fontWeight: "500",
    flex: 1,
  },
  incomingRequestAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginLeft: 8,
  },
  incomingRequestActionText: {
    fontSize: 13,
    color: ACCENT,
    fontWeight: "600",
  },

  // ── Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: CARD_BG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 12,
    maxHeight: "80%",
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#d1d1d6",
    alignSelf: "center",
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: "bold", color: TEXT_PRIMARY },

  // ── Ride detail
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  detailText: { fontSize: 15, color: TEXT_PRIMARY },
  actionRow: { flexDirection: "row", gap: 12, marginTop: 20 },
  denyButton: {
    flex: 1,
    backgroundColor: RED,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
  },
  acceptButton: {
    flex: 1,
    backgroundColor: GREEN,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
  },
  actionDisabled: { opacity: 0.6 },
  actionText: { color: TEXT_INVERSE, fontSize: 16, fontWeight: "700" },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    gap: 8,
  },
  confirmedText: { fontSize: 16, fontWeight: "600", color: GREEN },
  viewProfileButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: ACCENT,
    backgroundColor: ACCENT_LIGHT,
  },
  viewProfileText: { fontSize: 15, fontWeight: "600", color: ACCENT },

  // ── Form
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#3c3c43",
    marginBottom: 6,
    marginTop: 16,
  },
  textInput: {
    backgroundColor: BG,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: TEXT_PRIMARY,
    borderWidth: 1,
    borderColor: BORDER,
  },
  dropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownText: { fontSize: 15, color: TEXT_PRIMARY, flex: 1 },
  dropdownMenu: {
    maxHeight: 180,
    backgroundColor: CARD_BG,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    marginTop: 4,
    overflow: "hidden",
  },
  dropdownItem: {
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: BG,
  },
  dropdownItemText: { fontSize: 14, color: TEXT_PRIMARY },
  daysRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  dayChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: BG,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  dayChipSelected: { backgroundColor: ACCENT, borderColor: ACCENT },
  dayChipText: { fontSize: 13, fontWeight: "600", color: "#636366" },
  dayChipTextSelected: { color: TEXT_INVERSE },
  submitButton: {
    flexDirection: "row",
    backgroundColor: ACCENT,
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 28,
    gap: 8,
  },
  submitButtonDisabled: { opacity: 0.55 },
  submitButtonText: { color: TEXT_INVERSE, fontSize: 16, fontWeight: "700" },

  // ── Custom Confirmation Modal
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  confirmBox: {
    backgroundColor: CARD_BG,
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  confirmTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: TEXT_PRIMARY,
    marginBottom: 12,
    textAlign: "center",
  },
  confirmMessage: {
    fontSize: 16,
    color: "#636366",
    marginBottom: 24,
    textAlign: "center",
    lineHeight: 22,
  },
  confirmButtons: {
    flexDirection: "row",
    gap: 12,
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmKeep: {
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: BORDER,
  },
  confirmKeepText: {
    fontSize: 16,
    fontWeight: "600",
    color: ACCENT,
  },
  confirmCancel: {
    backgroundColor: RED,
  },
  confirmCancelText: {
    fontSize: 16,
    fontWeight: "700",
    color: TEXT_INVERSE,
  },
});
