import {
  ACCENT,
  ACCENT_LIGHT,
  BG,
  BORDER,
  BORDER_LIGHT,
  CARD_BG,
  ERROR_ACTION,
  ERROR_BG,
  ERROR_BORDER,
  ERROR_DARK,
  ERROR_TEXT,
  GREEN,
  GREEN_LIGHT,
  ORANGE,
  ORANGE_LIGHT,
  RED,
  SHADOW,
  SURFACE_MUTED,
  SURFACE_SUBTLE,
  TEXT_INVERSE,
  TEXT_MUTED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_TERTIARY,
  WARN_BG,
  WARN_BORDER,
  WARN_TEXT,
} from '@/utils/constants';
import { StyleSheet } from 'react-native';

export const scheduleStyles = StyleSheet.create({
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ACCENT_LIGHT,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 12,
    gap: 8,
  },
  text: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: ACCENT,
  },
});

export const errorBoundaryStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  message: {
    fontSize: 16,
    color: TEXT_TERTIARY,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: ACCENT,
    borderRadius: 10,
  },
  retryText: {
    color: TEXT_INVERSE,
    fontWeight: '600',
  },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BG,
  },
  header: {
    paddingBottom: 12,
  },
  headerRefresh: {
    padding: 8,
    marginRight: -4,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: ERROR_BG,
    borderBottomWidth: 1,
    borderBottomColor: ERROR_BORDER,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  errorBannerBody: {
    flex: 1,
    minWidth: 0,
  },
  errorBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: ERROR_DARK,
    marginBottom: 4,
  },
  errorBannerText: {
    fontSize: 13,
    color: ERROR_TEXT,
    lineHeight: 18,
  },
  errorBannerRetry: {
    backgroundColor: ERROR_ACTION,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignSelf: 'center',
  },
  errorBannerRetryText: {
    color: TEXT_INVERSE,
    fontSize: 13,
    fontWeight: '700',
  },
  warnBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: WARN_BG,
    borderBottomWidth: 1,
    borderBottomColor: WARN_BORDER,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  warnBannerText: {
    flex: 1,
    fontSize: 13,
    color: WARN_TEXT,
    lineHeight: 18,
  },
  toggleBar: {
    flexDirection: 'row',
    backgroundColor: CARD_BG,
    paddingHorizontal: 20,
    paddingBottom: 12,
    gap: 8,
  },
  toggleTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: BORDER_LIGHT,
    gap: 6,
  },
  toggleTabActive: {
    backgroundColor: ACCENT,
  },
  toggleText: {
    fontSize: 15,
    fontWeight: '600',
    color: TEXT_SECONDARY,
  },
  toggleTextActive: {
    color: TEXT_INVERSE,
  },
  badge: {
    backgroundColor: BORDER,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  badgeOnActive: {
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: TEXT_SECONDARY,
  },
  badgeTextOnActive: {
    color: TEXT_INVERSE,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    marginTop: 12,
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 14,
    color: TEXT_MUTED,
    textAlign: 'center',
    lineHeight: 20,
  },
  activeContainer: {
    flex: 1,
  },
  mapContainer: {
    height: 240,
  },
  activeCards: {
    flex: 1,
  },
  upcomingList: {
    flex: 1,
  },
  upcomingContent: {
    paddingBottom: 40,
  },
  card: {
    backgroundColor: CARD_BG,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardDate: {
    fontSize: 13,
    fontWeight: '600',
    color: TEXT_SECONDARY,
  },
  cardDateLarge: {
    fontSize: 16,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: BORDER_LIGHT,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeActive: {
    backgroundColor: GREEN_LIGHT,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  dotGreen: {
    backgroundColor: GREEN,
  },
  dotOrange: {
    backgroundColor: ORANGE,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT_SECONDARY,
  },
  cardTime: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  cardTimeText: {
    fontSize: 14,
    fontWeight: '500',
    color: TEXT_PRIMARY,
  },
  locationBlock: {
    marginBottom: 14,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: BORDER_LIGHT,
    gap: 10,
  },
  avatarSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BORDER_LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarSmallImage: {
    width: '100%',
    height: '100%',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 15,
    fontWeight: '600',
    color: TEXT_PRIMARY,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 1,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ACCENT,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 6,
  },
  readyButton: {
    backgroundColor: GREEN,
  },
  completeButton: {
    backgroundColor: GREEN,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: TEXT_INVERSE,
    fontSize: 14,
    fontWeight: '700',
  },
  messageChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: ACCENT,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    gap: 5,
  },
  messageChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: ACCENT,
  },
  waitingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: ORANGE_LIGHT,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  cancelReadyButton: {
    borderWidth: 1.5,
    borderColor: RED,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  cancelReadyText: {
    fontSize: 13,
    fontWeight: '600',
    color: RED,
  },
  denyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1.5,
    borderColor: RED,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  denyButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: RED,
  },
  waitingText: {
    fontSize: 13,
    fontWeight: '500',
    color: ORANGE,
  },
  scheduledNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scheduledNoteText: {
    fontSize: 12,
    color: TEXT_MUTED,
  },
  etaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  etaText: {
    fontSize: 13,
    color: TEXT_SECONDARY,
    fontWeight: '500',
  },
});
