import {
  ACCENT,
  ACCENT_LIGHT,
  BG,
  BORDER,
  BORDER_DEFAULT,
  BORDER_LIGHT,
  CARD_BG,
  GREEN,
  ORANGE,
  PLACEHOLDER,
  RED,
  SHADOW,
  STAR_COLOR,
  TEXT_INVERSE,
  TEXT_MUTED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_TERTIARY,
} from '@/utils/constants';
import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  locationBadgeText: {
    fontSize: 12,
    color: GREEN,
    fontWeight: "500",
  },
  searchSection: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: CARD_BG,
    borderBottomWidth: 1,
    borderBottomColor: BORDER_DEFAULT,
    gap: 8,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: BG,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    marginLeft: 8,
    color: TEXT_PRIMARY,
  },
  filterIconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f0f7ff",
    justifyContent: "center",
    alignItems: "center",
  },
  filterActiveButton: {
    backgroundColor: ACCENT,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 15,
    color: TEXT_MUTED,
  },
  listContent: {
    padding: 16,
  },
  matchCard: {
    backgroundColor: CARD_BG,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  matchHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  matchInfo: {
    flex: 1,
    minWidth: 0,
  },
  matchName: {
    fontSize: 17,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    marginBottom: 4,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    flexWrap: "wrap",
    alignSelf: "flex-start",
  },
  rideCount: {
    fontSize: 12,
    color: TEXT_MUTED,
    marginLeft: 4,
    flexShrink: 0,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  detailText: {
    fontSize: 12,
    color: TEXT_TERTIARY,
  },
  separator: {
    fontSize: 12,
    color: "#ccc",
    marginHorizontal: 2,
  },
  scoreContainer: {
    alignItems: "center",
    backgroundColor: "#f0f7ff",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 8,
  },
  scoreValue: {
    fontSize: 16,
    fontWeight: "700",
    color: ACCENT,
  },
  scoreLabel: {
    fontSize: 10,
    color: ACCENT,
    fontWeight: "500",
  },
  bio: {
    fontSize: 14,
    color: TEXT_TERTIARY,
    lineHeight: 20,
    marginBottom: 12,
  },
  cardActions: {
    flexDirection: "row",
    gap: 8,
  },
  viewMoreButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#f0f7ff",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: ACCENT,
  },
  viewMoreButtonText: {
    color: ACCENT,
    fontSize: 14,
    fontWeight: "600",
    marginRight: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: CARD_BG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: TEXT_PRIMARY,
  },
  filterSection: {
    marginBottom: 24,
  },
  filterLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    marginBottom: 12,
  },
  filterValue: {
    color: ACCENT,
  },
  distanceChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ratingFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: BG,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: BORDER_DEFAULT,
    gap: 4,
  },
  filterChipActive: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  filterChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: TEXT_PRIMARY,
  },
  filterChipTextActive: {
    color: TEXT_INVERSE,
  },
  clearFiltersButton: {
    padding: 12,
    alignItems: "center",
  },
  clearFiltersText: {
    fontSize: 14,
    color: RED,
    fontWeight: "600",
  },
  applyButton: {
    backgroundColor: ACCENT,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  applyButtonText: {
    color: TEXT_INVERSE,
    fontSize: 18,
    fontWeight: "600",
  },
});
